/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'contactInfo' : string,
  'specialRequests' : string,
  'travelDates' : string,
  'tourId' : bigint,
  'groupSize' : bigint,
}
export interface ContactInfo {
  'businessHours' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
}
export interface Inquiry {
  'id' : bigint,
  'customerName' : string,
  'contactInfo' : string,
  'message' : string,
}
export interface Tour {
  'id' : bigint,
  'destination' : string,
  'duration' : bigint,
  'description' : string,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGalleryImage' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'addTour' : ActorMethod<[string, bigint, bigint, string], bigint>,
  'bookTour' : ActorMethod<
    [string, string, bigint, string, bigint, string],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllTours' : ActorMethod<[], Array<Tour>>,
  'getBookingsByGroupSize' : ActorMethod<[], Array<Booking>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getGalleryImagesById' : ActorMethod<[], Array<GalleryImage>>,
  'getInquiriesByName' : ActorMethod<[], Array<Inquiry>>,
  'getTourById' : ActorMethod<[bigint], Tour>,
  'getToursByDestination' : ActorMethod<[], Array<Tour>>,
  'submitInquiry' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];