/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'specialRequests' : IDL.Text,
  'travelDates' : IDL.Text,
  'tourId' : IDL.Nat,
  'groupSize' : IDL.Nat,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'message' : IDL.Text,
});
export const Tour = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const ContactInfo = IDL.Record({
  'businessHours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [],
      ['oneway'],
    ),
  'addTour' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'bookTour' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'getBookingsByGroupSize' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getGalleryImagesById' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getInquiriesByName' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getTourById' : IDL.Func([IDL.Nat], [Tour], ['query']),
  'getToursByDestination' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'specialRequests' : IDL.Text,
    'travelDates' : IDL.Text,
    'tourId' : IDL.Nat,
    'groupSize' : IDL.Nat,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'message' : IDL.Text,
  });
  const Tour = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ContactInfo = IDL.Record({
    'businessHours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [],
        ['oneway'],
      ),
    'addTour' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'bookTour' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllTours' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'getBookingsByGroupSize' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getGalleryImagesById' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getInquiriesByName' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getTourById' : IDL.Func([IDL.Nat], [Tour], ['query']),
    'getToursByDestination' : IDL.Func([], [IDL.Vec(Tour)], ['query']),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };